## Exercise 1: [Pocketful of Sunshine](https://www.youtube.com/watch?v=gte3BoXKwP0)

Answer the following questions by creating a pattern
that satisfies the test cases listed below. To form the test case vector,
combine the listed cases together and use the appropriate `re` function
that **displays** the pattern match inline.

### a

Any letter in your first name in lower case.

- **Matches:** If your first name is `james`, then match any word with:
      `j`, `a`, `m`, `e`, or `s`.
- **Test cases:** `"james"`, `"morgan"`, `"tom"`, `"nicole"`, `"will"`, `"sandra"`, `"charlize"`, `"meryl"`, and `"samuel`.

In [1]:
import os
import sys
import pandas as pd
import re

print(f"python: {sys.version}")
print(f"pandas: {pd.__version__}")
print(f"re: {re.__version__}")

try:
  from google.colab import drive
  is_google_colab = True

  print("Notebook is on Google CoLab")
except:
  is_google_colab = False
  print("Notebook is being run locally or through another source.")

python: 3.12.10 | packaged by conda-forge | (main, Apr 10 2025, 22:08:16) [MSC v.1943 64 bit (AMD64)]
pandas: 2.2.3
re: 2.2.1
Notebook is being run locally or through another source.

In [7]:
def search_pattern(data, pattern):
  import re
  return [bool(re.search(pattern = pattern, string = x)) for x in data]

def extract_all_patterns(data, pattern):
  import re
  return [re.findall(pattern, x) for x in data]

def obtain_match(single_string, pattern):
  import re

  # only operate on a single value
  match = re.search(pattern, single_string)

  # Retrieve the matched value if it succeeds.
  if match:
    return match.group()

  # Match did not succeed
  return None

def extract_matches(data, pattern):
  return [obtain_match(single_string, pattern) for single_string in data]

In [57]:
names = ["james", "morgan", "tom", "nicole", "will", "sandra", "charlize", "meryl", "samuel"]

## code here
print([re.findall(r'[boluwatife]', string) for string in names])
print([x for x in names if search_pattern(names, r'[boluwatife]')])

[['a', 'e'], ['o', 'a'], ['t', 'o'], ['i', 'o', 'l', 'e'], ['w', 'i', 'l', 'l'], ['a', 'a'], ['a', 'l', 'i', 'e'], ['e', 'l'], ['a', 'u', 'e', 'l']]
['james', 'morgan', 'tom', 'nicole', 'will', 'sandra', 'charlize', 'meryl', 'samuel']

### b

_Only_ Uppercase letters.

- **Matches:** "HELLOWORLD" but not "Hello World!", "HELLO WORLD", "hello world", or "helloworld".
  - _Hint:_ Anchors and quantifiers are your friend.
- **Test cases:** `"today is the DAY!"`, `"GOILLINI"`, `"Orange and Blue"`, `"CAPS LOCK"`, `"STAT"`, `"R2D2"`, `"python"`.

In [23]:
uppercase = ["today is the DAY!","GOILLINI","Orange and Blue","CAPS LOCK","STAT","R2D2","python"]

## code here
pattern = r"^[A-Z]*[^ ][A-Z]*[A-Z]$"
print([re.findall(pattern, string) for string in uppercase])

[[], ['GOILLINI'], [], [], ['STAT'], [], []]

### c

Alphanumeric password between 5 and 7 characters long

- **Matches:** 5 - 7 characters that contains only a-z, A-Z, or 0-9.
- **Test Cases:** `"seeing4Miles"`, `"h@llowed1"`, `"pie2Go"`, `"sunsun"`, `"laugh2Jokes"`

In [59]:
password = ["seeing4Miles","h@llowed1","pie2Go","sunsun","laugh2Jokes"]

## code here
pattern = r"^[A-Za-z0-9]{5,7}$"
print([re.findall(pattern, string) for string in password])

[[], [], ['pie2Go'], ['sunsun'], []]

### d

Any numbers between 1 and 9999

- **Matches:** 1, 2, ..., 42, ..., 180, ..., 999. Does _not_ match: 001, 05 ...

- **Test Cases:** `"001"`, `"1"`, `"15"`, `"891"`, `"05"`, `"0"`, `"999"`, `"0599"`, `"5566"`

In [60]:
numbers = ["001","1","15","891","05","0","999","0599","5566"]

## code here
pattern = r"^[1-9]{1,4}"
print([re.findall(pattern, string) for string in numbers])

[[], ['1'], ['15'], ['891'], [], [], ['999'], [], ['5566']]

### e

Sentences or questions that being with a capital letter and end with proper punctuation such as `!`, `?`, and `.`

- **Matches:** "How are you today?", "Goodbye Pete." Does _not_ match "good morning." or "Good Morning"
- **Test Cases:** `"What's your favorite color?"`, `"I am 10 years old!"`, `"re is a package."`, `"Go green to save the planet."`

In [134]:
sentences = ["What's your favorite color?",
             "I am 10 years wold!",
             "re is a package.",
             "Go green to save the planet."]

## code here
pattern = r"^[A-Z][0-9 a-z']{1,}[!?.]$"
print([re.findall(pattern, string) for string in sentences])

[["What's your favorite color?"], ['I am 10 years wold!'], [], ['Go green to save the planet.']]

# Exercise 2: Root Canal

Answer the following questions by creating a pattern
that satisfies the test cases listed while **extracting** the requested information from the string. To form the test case vector, combine the listed cases together and use the appropriate `re` function.

## a

Find and extract all of the stock ticker symbols.

- **Matches:** 2-5 uppercase letters consecutive uppercase letters
- **Test Cases:**
  - `"Apple (AAPL) reported strong earnings"`
  - `"MSFT and GOOGL are up today"`
  - `"The S&P 500 includes stocks like TSLA and AMZN"`
  - `"Check out NYSE:IBM for updates"`

In [1]:
text = [
  "Apple (AAPL) reported strong earnings",
  "MSFT and GOOGL are up today",
  "The S&P 500 includes stocks like TSLA and AMZN",
  "Check out NYSE:IBM for updates"
]

## code here

## b

Remove all HTML tags, leaving only the text content.

- **Matches:** Matches any HTML tag (e.g. `<tag></tag>`) and removes them.
- **Test Cases:**
  - `"<p>This is a <strong>great</strong> product!</p>"`
  - `"<div class='review'>Best purchase <em>ever</em>!</div>"`
  - `"<span style='color:red'>Highly recommended</span>"`

In [ ]:
text = [
  "<p>This is a <strong>great</strong> product!</p>",
  "<div class='review'>Best purchase <em>ever</em>!</div>",
  "<span style='color:red'>Highly recommended</span>"
]

## c

Extract hashtag references from embedded text.

- **Matches:** `#text` and extracts the value `#text`
- **Test Cases:** `"no tag"`, `"#python #stats"`, `"hi #imsiinterns"`, `"my #regex is #improving"`

In [ ]:
text = ["no tag","#python #stats","hi #imsiinterns","my #regex is #improving"]


## code here

## d

Match and Extract the Dimensions of a Monitor

- **Matches:** Three to four numbers followed by an `x` and then 3 to 4 more numbers.

- **Test Cases:** `"640x480"`, `"800x600"`, `"960x720"`, `"1024x768"`, `"1920x1200"`, `"2560x1600"`

In [ ]:
dimensions = ["640x480","800x600","960x720","1024x768","1920x1200","2560x1600"]

## code here

## e

Isolate file IDs from file extensions

- **Matches:** `file_xxxxx.pdf`, extracts `file_xxxxx`, and discards file extensions (e.g. `.pdf`, `.png`)
  - _Hint:_ Extract and then replacement to retrieve only `file_xxxx`
- **Test Cases**: `"file_transcript.pdf"`, `"file_imsi_sol.ipynb"`, `"file_grad_shot.png"`, `"991.docx"`, `"grades.xls"`
  - **Note** `991.docx` and `grade.xls` are **not** valid and should be _excluded_ during the extract portion.

In [ ]:
file_names = ["file_transcript.pdf","file_imsi_sol.ipynb","file_grad_shot.png","991.docx","grade.xlsj"]


## code here

# Exercise 3: File Name Meta Data

Oh no! The same group of scientists who were working on collecting data related to
vapor pressure deficiency -- a metric that combines temperature and relative humidity data
-- across **thousands** of plot locations in Illinois to address the invasive
understory plant [Amur honeysuckle (Lonicera maackii)](https://en.wikipedia.org/wiki/Lonicera_maackii)
had an even larger mishap with how their sensors tracked metadata about the
locations.

Unfortunately, the research assistants helping the scientists made an
even more egregious error with how certain sensors labelled the data. Seeing
as you did such a great job last time, your contact within the lab sent over the
following file names:

- P1-A14-S10_20180122.csv
- P342-A23-S333_20180522.csv
- P3-A1-S6_20180221.csv
- P15-A1-S14.20181029.csv
- P1441-A3-S2.20161001.csv
- P91-A4-S1.20181103.csv
- P2-A52-S50.20190115.csv
- P2-A2-S12.20190116.csv
- P2-A2-S25.20190117.csv

Help the scientist out by writing _Python_ code that extracts the metadata from the
file name and _stores_ it into a pandas `Data Frame`. **The _Python_ code should primarily
extract the metadata using regular expressions.** The final `Data Frame` should
have the following variables:

- `plot`
- `area`
- `sensor`
- `year`
- `month`
- `day`

The file name is _thankfully_  organized such that:

- `P`: denotes the plot;
- `A`: denotes the area on the plot a sensor was placed;
- `S`: denotes the sensor; and
- `YYYYMMDD` denotes the Year Month and Day format of the sensor.

**Example Output:**

```
  plot area sensor year month day
    P1  A14    S10 2018     1  22
  P342  A23   S333 2018     5  22
    P3   A1     S6 2018     2  21
   P15   A1    S14 2018    10  29
 P1441   A3     S2 2016    10   1
   P91   A4     S1 2018    11   3
    P2  A52    S50 2019     1  15
    P2   A2    S12 2019     1  16
    P2   A2    S25 2019     1  17
```

In [122]:
import pandas as pd
import re

# Load file names
x = [
  "P1-A14-S10_20180122.csv",
  "P342-A23-S333_20180522.csv",
  "P3-A1-S6_20180221.csv",
  "P15-A1-S14.20181029.csv",
  "P1441-A3-S2.20161001.csv",
  "P91-A4-S1.20181103.csv",
  "P2-A52-S50.20190115.csv",
  "P2-A2-S12.20190116.csv",
  "P2-A2-S25.20190117.csv"
]

files = pd.Series(x)

files_add_commas = files.str.replace('([0-9]+)-([A-Z]+)', r'\1, \2', regex = True)

files_add_commas = files_add_commas.str.replace('([0-9]+)_([0-9]+)', r'\1, \2', regex = True)

files_add_commas = files_add_commas.str.replace('([0-9]+).(20)', r'\1, \2', regex = True)

files_add_commas = files_add_commas.str.replace('(201[0-9])([0-9]{2})([0-9]{2})', r'\1, \2, \3', regex = True)

files_add_commas = files_add_commas.str.replace('([0-9]{2})(.csv)', r'\1', regex = True)

files_add_commas_split = files_add_commas.str.split(pat=", ", expand = True)

col_names = ['plot', 'area', 'sensor', 'year', 'month', 'day']
new_file = files_add_commas_split
new_file.columns = col_names

new_file['year'] = new_file['year'].astype(int)
new_file['month'] = new_file['month'].astype(int)
new_file['day'] = new_file['day'].astype(int)

new_file

    plot area sensor  year  month  day
0     P1  A14    S10  2018      1   22
1   P342  A23   S333  2018      5   22
2     P3   A1     S6  2018      2   21
3    P15   A1    S14  2018     10   29
4  P1441   A3     S2  2016     10    1
5    P91   A4     S1  2018     11    3
6     P2  A52    S50  2019      1   15
7     P2   A2    S12  2019      1   16
8     P2   A2    S25  2019      1   17

In [142]:
x = [
  "P1-A14-S10_20180122.csv",
  "P342-A23-S333_20180522.csv",
  "P3-A1-S6_20180221.csv",
  "P15-A1-S14.20181029.csv",
  "P1441-A3-S2.20161001.csv",
  "P91-A4-S1.20181103.csv",
  "P2-A52-S50.20190115.csv",
  "P2-A2-S12.20190116.csv",
  "P2-A2-S25.20190117.csv"
]

files = pd.Series(x)

files_add_commas = files.str.replace('(P[0-9]+)-(A[0-9]+)-(S[0-9]+)([_.])(201[0-9])([0-9]{2})([0-9]{2})(.csv)', r'\1, \2, \3, \5, \6, \7', regex = True)

files_add_commas

files_add_commas_split = files_add_commas.str.split(pat=", ", expand = True)

col_names = ['plot', 'area', 'sensor', 'year', 'month', 'day']
new_file = files_add_commas_split
new_file.columns = col_names

new_file['year'] = new_file['year'].astype(int)
new_file['month'] = new_file['month'].astype(int)
new_file['day'] = new_file['day'].astype(int)

new_file

    plot area sensor  year  month  day
0     P1  A14    S10  2018      1   22
1   P342  A23   S333  2018      5   22
2     P3   A1     S6  2018      2   21
3    P15   A1    S14  2018     10   29
4  P1441   A3     S2  2016     10    1
5    P91   A4     S1  2018     11    3
6     P2  A52    S50  2019      1   15
7     P2   A2    S12  2019      1   16
8     P2   A2    S25  2019      1   17

# Exercise 4: Living the Pandas Loca!

### a

Given a Pandas DataFrame and tweet data, please extract the username mention from the tweet data, e.g. `@username`.

In [ ]:
import pandas as pd
import re

df = pd.DataFrame({
  'tweets': ['What drives me nuts about the @github API docs ',
            'Apple will allow Linux VMs to run Intel apps with Rosetta in macOS Ventura by @AndrewWrites',
            'Congrats to our top author of the week: @cassidoo! Thanks for sharing your insights with the community 🌟',
            '#todayisagoodday you know?']
})

print("DataFrame:")
display(df)

# code here

### b

Uh-oh, the survey data merged together everyone's full name! Please split the full name into three columns: `first`, `middle`, and `last`.

In [4]:
import pandas as pd
df = pd.DataFrame({
    'fullname': ["Morgan Freeman", "Tom Hanks", "Nicole Kidman", "Will Smith",
                 "Sandra Bullock", "Charlize Theron", "Meryl Streep", "Samuel Leroy Jackson"],
    'age': [85, 66, 52, 36, 53, 44, 70, 65]
})


print("DataFrame:")
display(df)

# code here

DataFrame:

               fullname  age
0        Morgan Freeman   85
1             Tom Hanks   66
2         Nicole Kidman   52
3            Will Smith   36
4        Sandra Bullock   53
5       Charlize Theron   44
6          Meryl Streep   70
7  Samuel Leroy Jackson   65

### c

Another data scientist was working on a script to improve automatic updates of enrollment information at various schools. The data scientist accidently put into production a script that prefixed each variable with `TEST_` and, then, the variable name. Moreover, the each column was named using uppercase, which goes against the policy. Please remove the `TEST_` prefix and convert the column names inside of the Pandas data frame to lowercase.

In [ ]:
import pandas as pd
df = pd.DataFrame({
    'TEST_SCHOOL': ['UIUC', 'UChicago', 'Duke', 'Northwestern', 'Berkeley'],
    'TEST_ENROLLED': [1000, 2000, 3000, 4000, 5000],
    'TEST_DATE': ['11/15/2019','02/20/2023','05/19/2025','03/12/2025','12/01/2024'],
})
print("DataFrame:")
display(df)

## code here

## d

You've been called in to analyzing log file data from a web server that powers your company's ecommerce store. Please:

1. Extract IP addresses
1. Extract timestamps
1. Extract HTTP methods (GET, POST, DELETE, HEAD, OPTIONS, etc.)
1. Extract response codes (200, 404, 403, 500, 301, etc.)
1. Extract file paths

In [7]:
import pandas as pd

# Web server log data (Apache Common Log Format)
log_data = {
    'log_entry': [
        '192.168.1.1 - - [10/Dec/2023:13:55:36 +0000] "GET /index.html HTTP/1.1" 200 2326',
        '10.0.0.1 - - [10/Dec/2023:13:56:42 +0000] "POST /api/login HTTP/1.1" 404 512',
        '172.16.0.100 - - [10/Dec/2023:13:57:01 +0000] "GET /about.html HTTP/1.1" 200 1045',
        '203.0.113.195 - - [10/Dec/2023:14:15:22 +0000] "GET /images/logo.png HTTP/1.1" 200 15420',
        '198.51.100.178 - - [10/Dec/2023:14:16:05 +0000] "POST /api/users HTTP/1.1" 201 89',
        '192.168.1.50 - - [10/Dec/2023:14:17:33 +0000] "GET /products/item/123 HTTP/1.1" 200 3456',
        '10.0.0.25 - - [10/Dec/2023:14:18:12 +0000] "DELETE /api/posts/456 HTTP/1.1" 204 0',
        '172.16.254.1 - - [10/Dec/2023:14:19:45 +0000] "GET /nonexistent.html HTTP/1.1" 404 1024',
        '203.0.113.42 - - [10/Dec/2023:14:20:01 +0000] "PUT /api/profile/789 HTTP/1.1" 200 234',
        '198.51.100.99 - - [10/Dec/2023:14:21:33 +0000] "GET /css/styles.css HTTP/1.1" 304 0',
        '192.168.1.105 - - [10/Dec/2023:14:22:15 +0000] "GET /js/app.js HTTP/1.1" 200 8765',
        '10.0.0.88 - - [10/Dec/2023:14:23:44 +0000] "POST /contact/submit HTTP/1.1" 500 2048',
        '172.16.0.200 - - [10/Dec/2023:14:24:12 +0000] "GET /downloads/file.pdf HTTP/1.1" 200 524288',
        '203.0.113.150 - - [10/Dec/2023:14:25:03 +0000] "GET /search?q=python+regex HTTP/1.1" 200 4567',
        '198.51.100.33 - - [10/Dec/2023:14:26:18 +0000] "GET /admin/dashboard HTTP/1.1" 403 567',
        '192.168.1.201 - - [10/Dec/2023:14:27:55 +0000] "PATCH /api/settings HTTP/1.1" 200 123',
        '10.0.0.150 - - [10/Dec/2023:14:28:33 +0000] "GET /data/export.csv HTTP/1.1" 200 98765',
        '172.16.100.50 - - [10/Dec/2023:14:29:07 +0000] "HEAD /api/health HTTP/1.1" 200 0',
        '203.0.113.75 - - [10/Dec/2023:14:30:42 +0000] "GET /blog/post/machine-learning HTTP/1.1" 200 7890',
        '198.51.100.11 - - [10/Dec/2023:14:31:19 +0000] "POST /api/upload HTTP/1.1" 413 256',
        '192.168.1.88 - - [10/Dec/2023:14:32:05 +0000] "GET /sitemap.xml HTTP/1.1" 200 1234',
        '10.0.0.199 - - [10/Dec/2023:14:33:28 +0000] "GET /api/stats HTTP/1.1" 503 512',
        '172.16.50.25 - - [10/Dec/2023:14:34:44 +0000] "OPTIONS /api/cors HTTP/1.1" 200 0',
        '203.0.113.88 - - [10/Dec/2023:14:35:12 +0000] "GET /mobile/app.html HTTP/1.1" 301 0',
        '198.51.100.200 - - [10/Dec/2023:14:36:55 +0000] "GET /robots.txt HTTP/1.1" 200 158'
    ]
}
df = pd.DataFrame(log_data)
print("DataFrame:")
display(df)

## code here

DataFrame:

                                            log_entry
0   192.168.1.1 - - [10/Dec/2023:13:55:36 +0000] "...
1   10.0.0.1 - - [10/Dec/2023:13:56:42 +0000] "POS...
2   172.16.0.100 - - [10/Dec/2023:13:57:01 +0000] ...
3   203.0.113.195 - - [10/Dec/2023:14:15:22 +0000]...
4   198.51.100.178 - - [10/Dec/2023:14:16:05 +0000...
5   192.168.1.50 - - [10/Dec/2023:14:17:33 +0000] ...
6   10.0.0.25 - - [10/Dec/2023:14:18:12 +0000] "DE...
7   172.16.254.1 - - [10/Dec/2023:14:19:45 +0000] ...
8   203.0.113.42 - - [10/Dec/2023:14:20:01 +0000] ...
9   198.51.100.99 - - [10/Dec/2023:14:21:33 +0000]...
10  192.168.1.105 - - [10/Dec/2023:14:22:15 +0000]...
11  10.0.0.88 - - [10/Dec/2023:14:23:44 +0000] "PO...
12  172.16.0.200 - - [10/Dec/2023:14:24:12 +0000] ...
13  203.0.113.150 - - [10/Dec/2023:14:25:03 +0000]...
14  198.51.100.33 - - [10/Dec/2023:14:26:18 +0000]...
15  192.168.1.201 - - [10/Dec/2023:14:27:55 +0000]...
16  10.0.0.150 - - [10/Dec/2023:14:28:33 +0000] "G...
17  172.16.100.50 - - [10/Dec/2023:14:29:07 +0000]...
18  203.0.113.75 - - [10/Dec/2023:14:30:42 +0000] ...
19  198.51.100.11 - - [10/Dec/2023:14:31:19 +0000]...
20  192.168.1.88 - - [10/Dec/2023:14:32:05 +0000] ...
21  10.0.0.199 - - [10/Dec/2023:14:33:28 +0000] "G...
22  172.16.50.25 - - [10/Dec/2023:14:34:44 +0000] ...
23  203.0.113.88 - - [10/Dec/2023:14:35:12 +0000] ...
24            Invalid log entry without proper format
25  198.51.100.200 - - [10/Dec/2023:14:36:55 +0000...